//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.30 at 07:41:38 PM PST 
//


package com.manzia.shopping.reviews;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for reviewMatchType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="reviewMatchType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="reviewId" type="{http://www.w3.org/2001/XMLSchema}token"/>
 *         &lt;element name="reviewSku" type="{http://www.w3.org/2001/XMLSchema}token"/>
 *         &lt;element name="reviewCategory" type="{http://www.w3.org/2001/XMLSchema}token"/>
 *         &lt;element name="reviewTitle" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="reviewContent" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="reviewRating" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="reviewSubmitTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="reviewAuthor" type="{http://www.w3.org/2001/XMLSchema}token"/>
 *         &lt;element name="reviewSource" type="{http://www.w3.org/2001/XMLSchema}token"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "reviewMatchType", namespace = "http://www.manzia.com/ReviewMatchesXMLSchema", propOrder = {
    "reviewId",
    "reviewSku",
    "reviewCategory",
    "reviewTitle",
    "reviewContent",
    "reviewRating",
    "reviewSubmitTime",
    "reviewAuthor",
    "reviewSource"
})
public class ReviewMatchType {

    @XmlElement(namespace = "http://www.manzia.com/ReviewMatchesXMLSchema", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String reviewId;
    @XmlElement(namespace = "http://www.manzia.com/ReviewMatchesXMLSchema", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String reviewSku;
    @XmlElement(namespace = "http://www.manzia.com/ReviewMatchesXMLSchema", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String reviewCategory;
    @XmlElement(namespace = "http://www.manzia.com/ReviewMatchesXMLSchema", required = true)
    protected String reviewTitle;
    @XmlElement(namespace = "http://www.manzia.com/ReviewMatchesXMLSchema", required = true)
    protected String reviewContent;
    @XmlElement(namespace = "http://www.manzia.com/ReviewMatchesXMLSchema", required = true)
    protected BigDecimal reviewRating;
    @XmlElement(namespace = "http://www.manzia.com/ReviewMatchesXMLSchema", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar reviewSubmitTime;
    @XmlElement(namespace = "http://www.manzia.com/ReviewMatchesXMLSchema", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String reviewAuthor;
    @XmlElement(namespace = "http://www.manzia.com/ReviewMatchesXMLSchema", required = true)
    protected String reviewSource;

    /**
     * Gets the value of the reviewId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReviewId() {
        return reviewId;
    }

    /**
     * Sets the value of the reviewId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReviewId(String value) {
        this.reviewId = value;
    }

    /**
     * Gets the value of the reviewSku property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReviewSku() {
        return reviewSku;
    }

    /**
     * Sets the value of the reviewSku property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReviewSku(String value) {
        this.reviewSku = value;
    }

    /**
     * Gets the value of the reviewCategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReviewCategory() {
        return reviewCategory;
    }

    /**
     * Sets the value of the reviewCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReviewCategory(String value) {
        this.reviewCategory = value;
    }

    /**
     * Gets the value of the reviewTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReviewTitle() {
        return reviewTitle;
    }

    /**
     * Sets the value of the reviewTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReviewTitle(String value) {
        this.reviewTitle = value;
    }

    /**
     * Gets the value of the reviewContent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReviewContent() {
        return reviewContent;
    }

    /**
     * Sets the value of the reviewContent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReviewContent(String value) {
        this.reviewContent = value;
    }

    /**
     * Gets the value of the reviewRating property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getReviewRating() {
        return reviewRating;
    }

    /**
     * Sets the value of the reviewRating property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setReviewRating(BigDecimal value) {
        this.reviewRating = value;
    }

    /**
     * Gets the value of the reviewSubmitTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getReviewSubmitTime() {
        return reviewSubmitTime;
    }

    /**
     * Sets the value of the reviewSubmitTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setReviewSubmitTime(XMLGregorianCalendar value) {
        this.reviewSubmitTime = value;
    }

    /**
     * Gets the value of the reviewAuthor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReviewAuthor() {
        return reviewAuthor;
    }

    /**
     * Sets the value of the reviewAuthor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReviewAuthor(String value) {
        this.reviewAuthor = value;
    }
    
    /**
     * Gets the value of the reviewSource property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReviewSource() {
        return reviewSource;
    }

    /**
     * Sets the value of the reviewSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReviewSource(String value) {
        this.reviewSource = value;
    }

}
