//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.27 at 10:45:11 AM PST 
//


package com.manzia.shopping.ranking;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for rankResultType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="rankResultType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="rankQuality" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="rankRating" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "rankResultType", propOrder = {
    "rankQuality",
    "rankRating"
})
public class RankResultType {

    @XmlElement(required = true)
    protected String rankQuality;
    @XmlElement(required = true)
    protected BigDecimal rankRating;

    /**
     * Gets the value of the rankQuality property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRankQuality() {
        return rankQuality;
    }

    /**
     * Sets the value of the rankQuality property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRankQuality(String value) {
        this.rankQuality = value;
    }

    /**
     * Gets the value of the rankRating property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRankRating() {
        return rankRating;
    }

    /**
     * Sets the value of the rankRating property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRankRating(BigDecimal value) {
        this.rankRating = value;
    }

}
